version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-appdb}
    ports:
      - "5432:5432" # Открываем порт наружу только для отладки, можно убрать
    networks:
      - app-network
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: migration_service
    command: >
      bash -c "
      sleep 5 &&
      export DATABASE_URL=postgresql://postgres:assasin88@db:5432/moscow_mellows &&
      cd backend/migrations &&
      echo 'Переменная DATABASE_URL установлена:' $DATABASE_URL &&
      alembic upgrade head"
    volumes:
      # Монтируем код для доступа к миграциям
      - ./backend:/app/backend
    env_file:
      - .env # Загружаем переменные из .env файла
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONPATH: /app
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379" # Открываем порт наружу только для отладки, можно убрать
    networks:
      - app-network
    restart: unless-stopped

  user-server:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: user_server_app
    command: >
      bash -c "
      touch .env &&
      uvicorn servers.server_user:app --host 0.0.0.0 --port 8000"
    volumes:
      # Монтируем код для hot-reload во время разработки
      - ./backend:/app/backend
      - ./servers:/app/servers
      # Монтируем requirements для обновления зависимостей без пересборки
      - ./requirements.txt:/app/requirements.txt 
      # Монтируем общую папку для медиафайлов
      - ./private_media:/app/private_media 
    ports:
      - "8000:8000"
    env_file:
      - .env # Загружаем переменные из .env файла
    environment:
      # Переопределяем хост БД и Redis для контейнера
      DB_HOST: db 
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONPATH: /app  # Явно устанавливаем PYTHONPATH
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: unless-stopped

  admin-server:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: admin_server_app
    command: >
      bash -c "
      touch .env &&
      uvicorn servers.server_admin:app --host 0.0.0.0 --port 8001"
    volumes:
      # Монтируем код для hot-reload во время разработки
      - ./backend:/app/backend
      - ./servers:/app/servers
      # Монтируем requirements для обновления зависимостей без пересборки
      - ./requirements.txt:/app/requirements.txt
      # Монтируем общую папку для медиафайлов
      - ./private_media:/app/private_media
    ports:
      - "8001:8001"
    env_file:
      - .env # Загружаем переменные из .env файла
    environment:
      # Переопределяем хост БД и Redis для контейнера
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONPATH: /app  # Явно устанавливаем PYTHONPATH
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    volumes:
      # В production режиме не нужен hot-reload, поэтому монтируем только .env.local
      - ./frontend/.env.local:/app/.env.local
    ports:
      - "3000:3000"
    environment:
      # Используем имена сервисов вместо localhost
      NEXT_PUBLIC_API_URL: http://user-server:8000
      NEXT_ADMIN_API_URL: http://admin-server:8001
      NODE_ENV: production
    depends_on:
      - user-server
      - admin-server
    networks:
      - app-network
    # Вернем стандартную команду запуска
    command: npm start
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 