"""Add last_active column to User model

Revision ID: 158af34fcfe2
Revises: b3e7a4f8d961
Create Date: 2025-04-16 14:46:35.848285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158af34fcfe2'
down_revision = 'b3e7a4f8d961'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    # ### end Alembic commands ### 