"""add_url_slug_to_events

Revision ID: b3e7a4f8d961
Revises: 59e6e30f7552
Create Date: 2025-04-10 15:30:10.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e7a4f8d961'
down_revision = '59e6e30f7552'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку url_slug в таблицу events
    op.add_column('events', sa.Column('url_slug', sa.String(length=255), nullable=True, unique=True))
    
    # Заполняем url_slug для существующих записей, используя только латинские символы
    # Используем регулярное выражение, чтобы оставить только латинские буквы, цифры и заменить остальные на дефисы
    op.execute("""
        UPDATE events 
        SET url_slug = LOWER(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    title, 
                    '[^a-zA-Z0-9]', 
                    '-', 
                    'g'
                ),
                '-+', 
                '-', 
                'g'
            ) || '-' || id::text
        )
        WHERE url_slug IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'url_slug')
    # ### end Alembic commands ### 