"""Remove last_active column from User model

Revision ID: 7c94e6d32f5a
Revises: 158af34fcfe2
Create Date: 2023-07-10 14:30:35.848285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c94e6d32f5a'
down_revision = '158af34fcfe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ### 